---

- name: Schedule cron jobs
  cron:
    name: "{{ item.name | default(item.id) }}"
    cron_file: "ansible_cron_{{ item.id }}"
    user: "{{ item.user }}"
    hour: "{{ item.hour | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    job: "{{ item.job }}"
  with_items: crontabs
