---

- name: Check CA cert existence
  stat:
    path: "{{ ssl_dir }}/ca.pem"
  register: ssl_ca_cert_stat_out

- name: Include CA generation tasks
  include: gen-ca.yml
  when: not ssl_ca_cert_stat_out.stat.exists
