---

- name: Check cert existence
  stat:
    path: "{{ ssl_cert_dir }}/{{ ssl_cert.name }}.pem"
  run_once: "{{ false if cert_item.per_host is defined and cert_item.per_host else true }}"
  register: ssl_cert_stat_out

- name: Include cert generation tasks
  include: gen-cert.yml
  run_once: "{{ false if cert_item.per_host is defined and cert_item.per_host else true }}"
  when: not ssl_cert_stat_out.stat.exists
