---

# Set ssh_sshd_config
- name: Collect OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - default.yml

# This is no longer necessary as the base image sshd has been updated
# Install OpenSSH on SmartOS zones
#- include: smartos_zone_openssh.yml
#  when: ansible_distribution == 'SmartOS' and ansible_distribution_version < '16.1' and ansible_container == 'zone'

- name: Set sshd_config options (group)
  lineinfile:
    dest: "{{ ssh_config_dir }}/sshd_config"
    line: "{{ item.option }} {{ item.value }}"
    regexp: "^{{ item.option }} "
    state: present
    backup: yes
  with_flattened:
    - "{{ ssh_all_sshd_config }}"
    - "{{ ssh_group_sshd_config }}"
    - "{{ ssh_host_sshd_config }}"
  notify:
    - reload sshd
