---

- name: Include tasks for install type
  include_tasks: "{{ supervisord_install }}.yml"

- name: Install supervisor configs
  template:
    src: "templates/supervisor/{{ item }}.j2"
    dest: "{{ supervisord_conf_dir }}/{{ item }}.{{ supervisord_conf_ext }}"
  with_galaxyproject.general.inheritance_chain: "supervisor_configs"
  notify:
    - update supervisord

- name: Remove supervisor configs
  file:
    path: "{{ supervisord_conf_dir }}/{{ item }}.{{ supervisord_conf_ext }}"
    state: absent
  with_galaxyproject.general.inheritance_chain: "absent_supervisor_configs"
  notify:
    - update supervisord

- name: Ensure supervisord is enabled and running
  service:
    name: "{{ supervisord_service_name }}"
    enabled: yes
    state: started
  when: supervisord_service_name is defined
