---

- name: Set variables appropriate for virtualenv install type
  include_vars: virtualenv.yml

- name: Install virtualenv (apt)
  apt:
    name: python-virtualenv
  when: ansible_os_family == "Debian"

- name: Install virtualenv (yum)
  yum:
    name: python-virtualenv
  when: ansible_os_family == "RedHat"

- name: Install supervisor (virtualenv)
  pip:
    name: supervisor
    virtualenv: "{{ supervisord_prefix }}"
    virtualenv_command: "{{ pip_virtualenv_command | default(omit) }}"

- name: Create local supervisor directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ supervisord_conf_dir }}"
    - "{{ supervisord_log_dir }}"

- name: Install supervisord.conf
  template:
    src: supervisord.conf.j2
    dest: "{{ supervisord_conf_path }}"
  notify:
    - restart supervisord

- name: supervisord service install block
  block:

    - name: Detect systemd
      command: /usr/bin/pgrep -u root systemd
      register: systemd
      failed_when: False
      changed_when: False

    - name: Install init script (SysV init)
      template:
        src: "{{ ansible_distribution | lower }}.init.j2"
        dest: /etc/init.d/supervisor
        mode: "0755"
      when: systemd.rc != 0

    - name: Install service unit file (systemd)
      template:
        src: systemd.init.j2
        dest: /etc/systemd/system/supervisor.service
        mode: "0755"
      when: systemd.rc == 0

  when: supervisord_service_install
