---

- name: SmartOS LX Brand hostname tasks
  block:

    # Annoyingly, the builtin hostname module supports this via FileStrategy, but doesn't expose its functionalty
    # through the very limited set of `use` params you can choose from

    - name: Set hostname (immediate)
      command: "hostname {{ inventory_hostname }}"
      changed_when: false

    - name: Set hostname (persistent)
      copy:
        content: "{{ inventory_hostname }}"
        dest: /etc/hostname
        mode: "0755"

  when: (hostname_strategy | default(none)) == "file"

- name: SmartOS LX Brand Debian tasks
  block:

    # I don't believe this is still necessary
    #- name: Hold back systemd
    #  dpkg_selections:
    #    name: systemd
    #    selection: hold

    # sendfile bug fixed in https://github.com/joyent/illumos-joyent/commit/b189ef943db9b29af9068d3b3b49bc364699da56 20200910T013122Z

    # resolv.conf is not maintained in newer manually-updated LX Brand Ubuntu zones
    - name: Include resolv role for Ubuntu LX Brand zones
      include_role:
        name: resolv
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '>=')

    - name: Create native ZFS mount-all service
      copy:
        src: zfs-mount.service
        dest: /etc/systemd/system/zfs-mount.service
        mode: "0644"

    - name: Enable native ZFS mount-all service
      systemd:
        name: zfs-mount.service
        enabled: true

  when: ansible_os_family == "Debian"

- name: SmartOS LX Brand Enterprise Linux tasks
  block:

    - name: Disable services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop: "{{ virtual_lx_disable_services_redhat[ansible_distribution_major_version] }}"

  when: ansible_os_family == "RedHat"
