---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: "{{ hostname_strategy |default(omit) }}"

- name: Include Amazon EC2 tasks
  include_tasks: amazon-ec2.yml
  when: ansible_system_vendor == "Amazon EC2"

- name: Include SmartOS LX Brand tasks
  include_tasks: lx-brand.yml
  when: ansible_system == "Linux" and ansible_virtualization_type == "zone"
