---

- name: Update cache and ensure apt-transport-https is installed
  apt:
    pkg: apt-transport-https
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Add APT keys
  apt_key:
    data: "{{ item.data | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    id: "{{ item.id | default(omit) }}"
    keyring: "{{ item.keyring | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  with_flattened:
    - all_apt_keys
    - group_apt_keys
    - host_apt_keys
  when: ansible_os_family == "Debian"

- name: Add APT repositories
  apt_repository:
    mode: "{{ item.mode | default(omit) }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state | default(omit) }}"
    update_cache: "{{ item.update_cache | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  with_flattened:
   - all_apt_repositories
   - group_apt_repositories
   - host_apt_repositories
  when: ansible_os_family == "Debian"
  register: apt_repository

- name: Update APT cache for repository addition
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian" and apt_repository.changed

- name: Install packages (apt)
  apt: pkg={{ item }}
  with_flattened:
    - all_packages
    - group_packages
    - host_packages
  when: ansible_os_family == "Debian"

- name: Install packages (yum)
  yum: pkg={{ item }}
  with_flattened:
    - all_packages
    - group_packages
    - host_packages
  when: ansible_os_family == "RedHat"

- name: Install packages (pkgin)
  pkgin: pkg={{ item }}
  with_flattened:
    - all_packages
    - group_packages
    - host_packages
  when: ansible_distribution == "SmartOS"
