---

- name: Remove clouds.yaml
  ansible.builtin.file:
    path: "{{ playbook_dir }}/clouds.yaml"
    state: absent
  delegate_to: localhost
  run_once: true
  become: false

- name: Remove additional secrets
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ item.dest }}"
    state: absent
  loop: "{{ os_secrets | default([]) }}"
  delegate_to: localhost
  run_once: yes
  no_log: yes
