---

- name: Write clouds.yaml
  ansible.builtin.copy:
    content: "{{ os_clouds_yaml | to_nice_yaml }}"
    dest: "{{ playbook_dir }}/clouds.yaml"
    mode: "0400"
  delegate_to: localhost
  run_once: true
  no_log: yes

- name: Write additional secrets
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ playbook_dir }}/{{ item.dest }}"
    mode: "0400"
  loop: "{{ os_secrets | default([]) }}"
  delegate_to: localhost
  run_once: yes
  loop_control:
    label: "{{ item.dest }}"
