---

- name: Create users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: local_users
  when: local_users is defined

- name: Set authorized keys
  authorized_key: user={{ item.name }} key="{% for authorized in item.authorized %}{{ sshkeys[authorized] ~ '\n' }}{% endfor %}" exclusive=yes
  with_items: authorized_key_users
