---

- name: Create groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_flattened:
    - "{{ all_groups }}"
    - "{{ group_groups }}"
    - "{{ host_groups }}"

- name: Create users (non-Solaris)
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_flattened:
    - "{{ all_users }}"
    - "{{ group_users }}"
    - "{{ host_users }}"
    - "{{ local_users }}"
