---

- name: Create groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_flattened:
    - "{{ all_groups | default([]) }}"
    - "{{ group_groups | default([]) }}"
    - "[{% for group_name in group_names %}{{ vars[group_name ~ '_group_groups'] ~ ', ' if group_name ~ '_group_groups' in vars else None }}{% endfor %}]"
    - "{{ host_groups | default([]) }}"

- name: Create users (non-Solaris)
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_flattened:
    - "{{ all_users | default([]) }}"
    - "{{ group_users | default([]) }}"
    - "[{% for group_name in group_names %}{{ vars[group_name ~ '_group_users'] ~ ', ' if group_name ~ '_group_users' in vars else None }}{% endfor %}]"
    - "{{ host_users | default([]) }}"
    - "{{ local_users | default([]) }}"  # legacy
