---

- name: Create user groups (Solaris)
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_flattened:
    - "{{ all_users | default([]) }}"
    - "{{ group_users | default([]) }}"
    - "[{% for group_name in group_names %}{{ vars[group_name ~ '_group_users'] ~ ', ' if group_name ~ '_group_users' in vars else None }}{% endfor %}]"
    - "{{ host_users | default([]) }}"
    - "{{ local_users | default([]) }}"  # legacy
  when: item.group is defined

- name: Create users (Solaris)
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    password: "{{ item.password | default('NP') }}"
    update_password: "{{ item.update_password | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_flattened:
    - "{{ all_users | default([]) }}"
    - "{{ group_users | default([]) }}"
    - "[{% for group_name in group_names %}{{ vars[group_name ~ '_group_users'] ~ ', ' if group_name ~ '_group_users' in vars else None }}{% endfor %}]"
    - "{{ host_users | default([]) }}"
    - "{{ local_users | default([]) }}"  # legacy
