---

- name: Collect user groups for authorized keys
  command: id -gn {{ item.name }}
  with_items: "{{ _common_authorized_key_users }}"
  changed_when: no
  register: authorized_key_groups_out

- name: Ensure home directories exist for authorized_key
  file:
    path: "~{{ item.item.name }}"
    state: directory
    owner: "{{ item.item.name }}"
    group: "{{ item.stdout }}"
    mode: 0755
  with_items: "{{ authorized_key_groups_out.results }}"
  loop_control:
    label: "{{ item.item.name }}"

- name: Set authorized keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{% for authorized in item.authorized %}{{ sshkeys[authorized] ~ '\n' }}{% endfor %}"
    exclusive: "{{ item.exclusive | default('yes') }}"
  with_items: "{{ _common_authorized_key_users }}"

- name: Collect user groups for private keys
  command: id -gn {{ item.name }}
  with_items: "{{ _common_private_key_users }}"
  changed_when: no
  register: private_key_groups_out

- name: Ensure ~/.ssh directories exist for installing private keys
  file:
    path: "~{{ item.item.name }}"
    state: directory
    owner: "{{ item.item.name }}"
    group: "{{ item.stdout }}"
    mode: 0755
  with_items: "{{ private_key_groups_out.results }}"
  loop_control:
    label: "{{ item.item.name }}"

- name: Install private keys
  copy:
    content: "{{ sshprivatekeys[item.key] }}"
    dest: "~{{ item.0.name }}/.ssh/{{ item.file }}"
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    mode: 0600
  with_subelements:
    - "{{ _common_private_key_users }}"
    - keys
