---

- name: Install nvme-cli on EC2 instances
  include_role:
    name: packages
  vars:
    override_packages:
      - nvme-cli

- name: Install EC2 udev script
  copy:
    src: ebs-nvme-mapping.sh
    dest: /sbin/ebs-nvme-mapping.sh
    mode: "0755"
  notify:
    - trigger udevd

- name: Install EC2 udev rule
  copy:
    content: |
      SUBSYSTEM=="block", KERNEL=="nvme[0-9]*n[0-9]*", ATTRS{model}=="Amazon Elastic Block Store", PROGRAM+="/sbin/ebs-nvme-mapping.sh /dev/%k" SYMLINK+="%c"
    dest: /etc/udev/rules.d/999-aws-ebs-nvme.rules
  notify:
    - trigger udevd
