---

- name: SmartOS LX Brand Debian tasks
  block:

    - name: Hold back systemd
      dpkg_selections:
        name: systemd
        selection: hold

    # sendfile bug fixed in https://github.com/joyent/illumos-joyent/commit/b189ef943db9b29af9068d3b3b49bc364699da56 20200910T013122Z

    # resolv.conf is not maintained in newer maually-updated LX Brand Ubuntu zones
    - name: Include resolv role for Ubuntu LX Brand zones
      include_role:
        name: resolv
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '>=')

    - name: Create native ZFS mount-all service
      copy:
        src: zfs-mount.service
        dest: /etc/systemd/system/zfs-mount.service
        mode: "0644"

    - name: Enable native ZFS mount-all service
      systemd:
        name: zfs-mount.service
        enabled: true

  when: ansible_os_family == "Debian"
