---

# TODO: Inspect lower priority lists (host_files > group_files > all_files) and
# do not copy lower priority files if the same `dest` is present in a higher
# priority list

- name: Copy files
  copy:
    backup: "{{ item.backup | default(omit) }}"
    content: "{{ item.content | default(omit) }}"
    dest: "{{ item.dest }}"
    directory_mode: "{{ item.directory_mode | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    validate: "{{ item.validate | default(omit) }}"
  with_flattened:
    - "{{ all_files }}"
    - "{{ group_files }}"
    - "[{% for group_name in group_names %}{{ vars[group_name ~ '_group_files'] ~ ', ' if group_name ~ '_group_files' in vars else None }}{% endfor %}]"
    - "{{ host_files }}"

- name: Copy templates
  template:
    backup: "{{ item.backup | default(omit) }}"
    dest: "{{ item.dest }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    validate: "{{ item.validate | default(omit) }}"
  with_flattened:
    - "{{ all_templates }}"
    - "{{ group_templates }}"
    - "[{% for group_name in group_names %}{{ vars[group_name ~ '_group_templates'] ~ ', ' if group_name ~ '_group_templates' in vars else None }}{% endfor %}]"
    - "{{ host_templates }}"
